### PR TITLE
Add nfcMessagePayload support

### PR DESCRIPTION
**Pull request by scottire**
See [here](https://developer.apple.com/videos/play/tech-talks/702) for details about an update to CoreNFC that allows reading NFC tags in the background on iPhone XS, iPhone XS Max, and iPhone XR with iOS 12.

**I haven't been able to test this** because I don't have one of the latest iPhones 👎 
If somebody wants to buy me one or test this and update it, either suit me 🤠

### CODE REVIEW

**Comment by chrisweight** [comment]
Ok, @scottire - I've _just_ managed to acquire and XR, so I'll try and find time to throw together a test project to see if this PR works.

**Comment by Bramzor** [comment]
Can you explain what this pull does exactly? Because currently a scanned NFC tag with an url (deeplink) will already propose the user to open the app as if it would be a normal deeplink.

**Comment by scottire** [comment]
I still haven’t been able to test but the ended purpose was giving the deep link url when a tag is scanned using NFC. 

Here is the documentation for this particular feature. I’m now not entirely convinced it’s a useful addition considering the deep links are handled the same as normal deep links.

**Comment by Bramzor** [comment]
@scottire Problem with NFC on iOS is that you need to start a specific listener before it can see an NFC tag while it would always be listening on the device itself which makes it easier in my point of view. I also think the benefits would be small and possible risks high. Havent done a lot of testing on Android with the deeplinking integration and NFC but if it's the same as on iOS, I would leave any NFC code out of the deeplinks plugin.

**Comment by scottire** [comment]
> Problem with NFC on iOS is that you need to start a specific listener before it can see an NFC tag

Not sure what you mean by this. This feature happens in the background, no need for a dedicated app or listener. “Allow users to scan NFC tags without an app using background tag reading.“

> Havent done a lot of testing on Android with the deeplinking integration and NFC but if it's the same as on iOS, I would leave any NFC code out of the deeplinks plugin.

From what I have seen, the way Android handles background NFC reading is completely different than iOS. Not sure if they treat deeplinks differently either.

I agree that there seems to be little benefit of adding this feature, especially considering the lack of activity on this pull request.

**Comment by chrisweight** [comment]
Ok, @scottire I've re-visited this, taken a look at the code and the comments above, I'm in agreement that this provides little benefit, will close

**Pull request closed without merging**
