### PR TITLE
Check url before handle and GooglePlus/Linkedin fix

### PR DESCRIPTION
**Pull request by Bramzor**
I combined the check url from @jasonz1987: #172 and a fix for preventing the plugin from breaking other plugins like GooglePlus #174 and probably LinkedIn as well: #145

Can someone confirm this fixes their issue too so we can get this fix merged?

### CODE REVIEW

**Comment by hiepxanh** [comment]
Please, merge this issue, It verry important for google plus login

**Comment by chrisweight** [comment]
@Bramzor - your modifications to plugin.xml won't work, preferences set in plugin.xml are designed for default values only: https://cordova.apache.org/docs/en/latest/plugin_ref/spec.html#preference

I've tested this and those preferences are _not_ available to the app.

You need to add them to the `<config-file target="config.xml" parent="/*">` stanza, so it'll look like:

```
    <config-file target="config.xml" parent="/*">
      <feature name="IonicDeeplinkPlugin">
        <param name="ios-package" value="IonicDeeplinkPlugin" onload="true" />
      </feature>
      <preference name="URL_SCHEME" value="$URL_SCHEME" />
      <preference name="DEEPLINK_SCHEME" value="$DEEPLINK_SCHEME" />
      <preference name="DEEPLINK_HOST" value="$DEEPLINK_HOST" />
    </config-file>
```

That should work then...

**Comment by Bramzor** [comment]
@chrisweight during the tests it did not popup, but I changed it per your directions. Still have to test the change so if you can test or are certain, sure go ahead and merge.

**Comment by elylucas** [comment]
@Bramzor,

I know this is an old issue, but was commenting out this line intentional?
https://github.com/ionic-team/ionic-plugin-deeplinks/pull/194/files#diff-a81a965e8561a00cddb371125b73c2a8aaa85534b49a0aeb68a996cc711ba3deR60

This seems to break any apps that also listen to URL changes that use ionic-plugin-deeplinks. That commented out line is also what is called in the main Cordova App Delegate. 

It seems to work fine if I uncomment it and let both the notifications go through, but wasn't sure if there was a reason the original notification isn't called anymore.

Thanks!

**Pull request merged**
