### PR TITLE
check url before handle link

### LINKED ISSUE #124: Plugin stops custom url schemes out of its control from being handled
I am using ionic 1 and encountered one problem. This plugin cannot handle custom url schemes to other plugins.

In the log below, the plugin stops my Wechat SSO login callback method which relies on custom url scheme **wxb00cac42c59bb5b3**.

`2017-08-08 19:07:33.059066+0800 pangmaomao[3196:694632] IonicDeepLinkPlugin: Handle link (internal) wxb00cac42c59bb5b3://oauth?code=021XiQ7z1TWsDd0ZEk5z1yxZ7z1XiQ7v&state=_1502190448416`
`2017-08-08 19:07:34.063903+0800 pangmaomao[3196:694632] retryHandleOpenURL`

The process is:

1. I click **Wechat login**, jumps to Wechat and login
2. After Wechat login succeeds, jumps back to my APP and nothing hanppends with the log above

Command the plugin was installed:
`ionic cordova plugin add ionic-plugin-deeplinks --variable URL_SCHEME=ivynote --variable DEEPLINK_SCHEME=https --variable DEEPLINK_HOST=ivynote.cn --variable ANDROID_PATH_PREFIX=/`

My system:

cli packages: (/usr/local/var/www/com.pangmaomao.app/node_modules)

    @ionic/cli-plugin-cordova : 1.6.2
    @ionic/cli-plugin-gulp    : 1.1.1
    @ionic/cli-plugin-ionic1  : 2.1.1
    @ionic/cli-utils          : 1.7.0
    ionic (Ionic CLI)         : 3.7.0

global packages:

    Cordova CLI : 7.0.1 
    Gulp CLI    : CLI version 3.9.0 Local version 3.9.1

local packages:

    Cordova Platforms : android 6.0.0 ios 4.4.0
    Ionic Framework   : unknown

System:

    Android SDK Tools : 25.2.5
    Node              : v6.11.1
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy        : 1.9.0 
    ios-sim           : 5.0.6 
    npm               : 5.3.0

### PR DESCRIPTION
**Pull request by jasonz1987**
fix #124

### CODE REVIEW

**Comment by Farmertjes** [comment]
Really like this PR as the way this plugin currently handles openUrl breaks other plugins

**Comment by chrisweight** [comment]
@jasonz1987 - We've just released `1.0.18` that incorporates 3 PR's that may actually fix this. Can you pull the latest and see if it helps, then feedback here and tag me please?

**Comment by Bramzor** [comment]
@chrisweight 
I'm using ionic-plugin-deeplinks@1.0.19 (info in package.json) and the deeplink plugin still gets triggered from URLS that have nothing to do with it. (For example google login oauth). I assume this push might fix it?

**Comment by Bramzor** [comment]
Tried this one as a possible fix for #193 but seems that the plugin is still triggered by Google OAuth even though that is what this pull request should prevent right?

**Comment by chrisweight** [comment]
@jasonz1987 - this has been superseded by #194 and once @Bramzor addresses a small issue, that should be merged and I'll publish an update

**Pull request closed without merging**
