### PR TITLE
Add backwards compatible cordova-ios 5.0.0 support for iOS

### PR DESCRIPTION
**Pull request by Farmertjes**
- adds non-deprecated openUrl method to AppDelegate
- adds cordova CDVPluginHandleOpenURLWithAppSourceAndAnnotationNotification notification for other cordova apps to handle

### CODE REVIEW

**Comment by nmshaikh** [comment]
@Farmertjes I tried to make your proposed change by modifying the AppDelegate+IonicDeeplink.m file directly through XCode. But when I try to navigate back to my app, it crashes (black screen) with the following error displayed in XCode. Sorry if my explanation is not clear enough, I'm quite a beginner here.

main m file


xcode output

**Comment by Farmertjes** [comment]
@nmshaikh You are right. I don't know how this got through. Fixing now.

**Comment by janpio** [comment]
Please post the link to your new PR when you created it @Farmertjes so we can upvote again. Thanks.

**Comment by rhazn** [comment]
I tried my hand on it here: https://github.com/ionic-team/ionic-plugin-deeplinks/pull/184 because it seemed like a simple fix and Farmertjes closed this. Not sure if I am missing something in the flow here but if not, maybe someone can help me test 😅

**Pull request closed without merging**
