### PR TITLE
Make compatible with cordova-ios 5.0.0

### PR DESCRIPTION
**Pull request by olivermuc**
Please also see conversation over at 
https://github.com/apache/cordova-ios/issues/532#issuecomment-464804742

### CODE REVIEW

**Comment by janpio** [comment]
Is there maybe a way to _add_ this instead of _changing_ this? Then the plugin would continue to work with older cordova-ios versions which would be preferrable.

**Comment by olivermuc** [comment]
It's a valid point, and while I was happy to get it to work at all, I'm not sure I know enough to make it backwards compatible. 
It may be as easy as duplicating the functions in question.
More than happy to do it if the original authors / owners could provide some insight.

**Comment by janpio** [comment]
Oh yeah, this was actually directed more at the general community here and not specifically you.

(You might want to update your title to include "Make compatible with cordova-ios 5.0.0" though - that is the most important bit here)

**Comment by Farmertjes** [comment]
I took your change and added backwards compatibility (and a small fix in regards to cordova notifications) and made a new Pull Request: https://github.com/ionic-team/ionic-plugin-deeplinks/pull/178

**Comment by BorntraegerMarc** [comment]
My universal links still seem to work with v1.0.17 of this plugin, tough 🤔

**Comment by chrisweight** [comment]
@olivermuc - So I've merged in https://github.com/ionic-team/ionic-plugin-deeplinks/pull/184 which solves the same issue. On next release could you update and test - and if you're still seeing problems log an issue?

**Pull request closed without merging**
